# Generated by Django 3.0.2 on 2020-01-13 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooceClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'chooces_clothes',
            },
        ),
        migrations.CreateModel(
            name='ColorClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'colors_clothes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='../static/img/noimage.jpg', upload_to='media/', verbose_name='Фотография профиля')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='SizeClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sizes_clothes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('address_novoi_poshti', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField()),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('chooce_clothes', models.ManyToManyField(related_name='order', to='admin_panel.ChooceClothes')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='ClothesView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_clothes', models.PositiveSmallIntegerField(choices=[(1, 'Футболка'), (2, 'Толстовка'), (3, 'Майка')], default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('old_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('count', models.PositiveSmallIntegerField()),
                ('color', models.ManyToManyField(related_name='clothes', to='admin_panel.ColorClothes')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Image')),
                ('size', models.ManyToManyField(related_name='clothes', to='admin_panel.SizeClothes')),
            ],
            options={
                'db_table': 'clothes_views',
                'ordering': ('datetime', 'enabled'),
            },
        ),
        migrations.AddField(
            model_name='chooceclothes',
            name='clothes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chooce_clothes', to='admin_panel.ClothesView'),
        ),
    ]
