# Generated by Django 3.0.2 on 2020-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesview',
            name='img',
            field=models.ImageField(default='../static/img/noimage.jpg', upload_to='media/', verbose_name='Фотография профиля'),
        ),
    ]
