# Generated by Django 3.0.2 on 2020-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20200126_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooceclothes',
            name='clothes',
        ),
        migrations.AddField(
            model_name='chooceclothes',
            name='clothes',
            field=models.ManyToManyField(related_name='chooce_clothes', to='admin_panel.ClothesView'),
        ),
    ]
