# Generated by Django 3.0.2 on 2020-01-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20200126_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooceclothes',
            name='clothes',
        ),
        migrations.AddField(
            model_name='chooceclothes',
            name='clothes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chooce_clothes', to='admin_panel.ClothesView'),
        ),
    ]
