# Generated by Django 3.0.2 on 2020-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20200126_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesview',
            name='img',
            field=models.URLField(verbose_name='Фотография одежды'),
        ),
    ]
